[package]
name = "grrs"
version = "0.1.0"
edition = "2024"

[dependencies]
ansi_term = "0.12.1"
anyhow = "1.0.100"
clap = { version = "4.5.48", features = ["derive"] }
clap-verbosity-flag = "3.0.4"
env_logger = "0.11.8"
indicatif = "0.18.0"
log = "0.4.28"
